-- Common Table Expression

SELECT * FROM PERSON.PERSON

-- WITH AS(CTE) - TABELA TEMPORÁRIA
WITH PESSOAS AS (
	SELECT PersonType, Title, FirstName FROM Person.Person
) SELECT * FROM PESSOAS


CREATE TABLE TESTE(
	COLUNA1 INT,
	COLUNA2 INT,
)

INSERT INTO TESTE VALUES (1, 1)
INSERT INTO TESTE VALUES (10, 25)
INSERT INTO TESTE VALUES (14, 16)
INSERT INTO TESTE VALUES (16, 1)
INSERT INTO TESTE VALUES (100, -7)

WITH PESSOAS AS (
	SELECT * FROM TESTE
) SELECT * FROM PESSOAS

SELECT 
COLUNA1,
COLUNA2,
COLUNA1 + COLUNA2 AS SOMA,
(COLUNA1 + COLUNA2) / 2 AS AVG
FROM TESTE

WITH PESSOAS AS (
	SELECT 
	COLUNA1,
	COLUNA2,
	COLUNA1 + COLUNA2 AS SOMA
	FROM TESTE

) SELECT
	COLUNA1,
	COLUNA2,
	SOMA/2 AS AVG_AVG
 FROM PESSOAS


 -- CTE com Joins encadeados

 SELECT * FROM Person.Person
 SELECT * FROM Person.PersonPhone
 SELECT * FROM Person.PhoneNumberType

 SELECT * FROM Person.PersonPhone AS T
 LEFT JOIN Person.PhoneNumberType AS TP
 ON T.PhoneNumberTypeID = TP.PhoneNumberTypeID

 SELECT
 P.FirstName,
 P.LastName,
 T.PhoneNumber,
 TP.Name
 FROM Person.Person AS P
 LEFT JOIN Person.PersonPhone AS T
 ON P.BusinessEntityID = T.BusinessEntityID
	LEFT JOIN Person.PhoneNumberType AS TP
	ON T.PhoneNumberTypeID = TP.PhoneNumberTypeID


WITH PESSOAS AS (
	SELECT * FROM Person.Person
),
TELEFONE AS (
	SELECT * FROM Person.PersonPhone
)
SELECT * FROM PESSOAS LEFT JOIN TELEFONE
ON PESSOAS.BusinessEntityID = TELEFONE.BusinessEntityID

-- SubQueries com IN
SELECT * FROM Person.Person
SELECT DISTINCT(EmailPromotion) FROM Person.Person

CREATE TABLE PROMOTION (
	PROMO_ID INT
)
INSERT INTO PROMOTION VALUES (0)
INSERT INTO PROMOTION VALUES (1)

SELECT DISTINCT PROMO_ID FROM PROMOTION

SELECT * FROM Person.Person
WHERE EmailPromotion IN (SELECT DISTINCT PROMO_ID FROM PROMOTION)


-- AUTO INCREMENT E TRIGGERS
CREATE TABLE TESTE_TRIGGER (
	ID INT IDENTITY(1, 1),
	NOME VARCHAR(30)
)

INSERT INTO TESTE_TRIGGER VALUES ('WESLLEY')
INSERT INTO TESTE_TRIGGER VALUES ('ALMEIDA')
INSERT INTO TESTE_TRIGGER VALUES (UPPER('buzz lightyear'))
INSERT INTO TESTE_TRIGGER VALUES (UPPER('Doli Guarana'))

SELECT * FROM TESTE_TRIGGER

-- TRIGGER
CREATE TRIGGER TRIGG_NAME
ON TESTE_TRIGGER
AFTER INSERT
AS
INSERT INTO TESTE_TRIGGER VALUES('Inserido pela Trigger');

CREATE TABLE USUARIOS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NOME VARCHAR(30),
	DATA_INSERCAO DATETIME
)

INSERT INTO USUARIOS VALUES('WESLLEY', '2020-05-10')
INSERT INTO USUARIOS VALUES('ALMEIDA', GETDATE())

ALTER TABLE USUARIOS
ADD STATUS INT

SELECT * FROM USUARIOS

UPDATE USUARIOS SET STATUS = 1

INSERT INTO USUARIOS VALUES('ROBERQSUEN', NULL, NULL)


CREATE TRIGGER TRIGG_UPDATE
ON USUARIOS
AFTER INSERT
AS
UPDATE USUARIOS SET STATUS = 0
WHERE DATA_INSERCAO IS NULL

INSERT INTO USUARIOS VALUES('TRUPEIR', NULL, NULL)


-- INDEX
SELECT * FROM Banco_AW.Person.Person

CREATE INDEX inx_pname
ON PERSON.PERSON (PersonType);

SELECT * FROM Banco_AW.Person.Person
WHERE PersonType = 'EM'

SELECT DISTINCT PersonType FROM Banco_AW.Person.Person


-- Lead e Lag
CREATE TABLE TABELA