CREATE TABLE TABELA(
	Data_Cadastro DATE,
	Valor INT
)

INSERT INTO TABELA VALUES ('2020-01-01', 12)
INSERT INTO TABELA VALUES ('2020-01-02', 8)
INSERT INTO TABELA VALUES ('2020-01-03', 5)
INSERT INTO TABELA VALUES ('2020-01-04', 4)
INSERT INTO TABELA VALUES ('2020-01-05', 7)
INSERT INTO TABELA VALUES ('2020-01-06', 16)
INSERT INTO TABELA VALUES ('2020-01-07', 21)


SELECT * FROM TABELA

SELECT
Valor,
Valor+1 AS SOMADO_1,
Valor-1 AS SUBTRAIDO_1
FROM TABELA

-- LAG(COLUMN REFERENCIA, POSICAO_ATRAS)
-- LEAD(COLUMN REFERENCIA, POSICAO_FRENTE) 
SELECT
Data_Cadastro,
Valor,
LAG(Valor, 1) OVER (ORDER BY Data_Cadastro ASC) AS COMMAND_LAG,
ISNULL(LAG(Valor, 1) OVER (ORDER BY Data_Cadastro ASC), 0) AS ISNULL_LAG,
Valor + ISNULL(LAG(Valor, 1) OVER (ORDER BY Data_Cadastro ASC), 0) AS SUM_LAG,
LEAD(Valor, 1) OVER (ORDER BY Data_Cadastro ASC) AS COMMAND_LEAD,
ISNULL(LEAD(Valor, 1) OVER (ORDER BY Data_Cadastro ASC), 0) AS ISNULL_LEAD,
Valor + ISNULL(LEAD(Valor, 1) OVER (ORDER BY Data_Cadastro ASC), 0) AS SUM_LEAD
FROM TABELA