CREATE TABLE FUNCIONARIOS (
	ID INT PRIMARY KEY,
	NOME VARCHAR(30),
	IDADE INT,
	SALARIO DECIMAL(4,2)
);

INSERT INTO FUNCIONARIOS VALUES (1,	'Weslley', 27, 40.00);
INSERT INTO FUNCIONARIOS VALUES (2,	'JOAO', 32, 80.00);
INSERT INTO FUNCIONARIOS VALUES (3,	'MARIA', 32, 99.00);
INSERT INTO FUNCIONARIOS VALUES (4,	'Weslley', 27, 55.00);
INSERT INTO FUNCIONARIOS VALUES (5,	'Weslley', 27, 40.00);
INSERT INTO FUNCIONARIOS VALUES (6,	'Weslley', 27, 55.00, 10.00);

SELECT NOME, IDADE, SALARIO FROM FUNCIONARIOS
SELECT DISTINCT NOME, IDADE, SALARIO FROM FUNCIONARIOS

ALTER TABLE FUNCIONARIOS ADD SALARIO_ANTIGO DECIMAL(4,2)
SELECT * FROM FUNCIONARIOS

UPDATE FUNCIONARIOS SET SALARIO_ANTIGO = 10

SELECT
NOME,
ID,
SALARIO_ANTIGO,
SALARIO AS SALARIO_NOVO,
SALARIO_ANTIGO + SALARIO AS SOMA_SALARIOS,
SALARIO - SALARIO_ANTIGO AS DIF_SALARIOS,
'VENDAS' AS AREA
FROM FUNCIONARIOS


SELECT 
MAX(SALARIO),
MIN(SALARIO),
AVG(SALARIO),
SUM(SALARIO)
FROM FUNCIONARIOS


SELECT
NOME,
ID,
SALARIO_ANTIGO,
SALARIO AS SALARIO_NOVO
FROM FUNCIONARIOS


SELECT
NOME, 
IDADE,
MAX(SALARIO) AS MAX,
MIN(SALARIO) AS MIN,
AVG(SALARIO) AS MEDIA,
SUM(SALARIO) AS SUM
FROM FUNCIONARIOS
GROUP BY  NOME, IDADE

