-- GERENCIANDO DADOS

-- INSERT
INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME)
VALUES('Weslley', 'Almeida');

SELECT * FROM ATTENDEE;

INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME, PHONE, EMAIL, VIP)
VALUES
('Lhais', 'Silverio', 12341234, 'lhais@silverio.com', 1),
('William', 'Almeida', 43214321, 'william@almeida.com', 0),
('Madalena', 'Nascimento', 09877890, 'madalena@nascimento.com', 0);

INSERT INTO ATTENDEE(FIRST_NAME, LAST_NAME, PHONE, EMAIL)
SELECT FIRST_NAME, LAST_NAME, PHONE, EMAIL
FROM SOME_OTHER_TABLE;

INSERT INTO COMPANY(NAME, DESCRIPTION, PRIMARY_CONTACT_ATTENDEE_ID)
VALUES('RexApp Solutions', 'A mobile app delivery service', 3);

-- DELETE
-- COMUMENTE E FEITO UM CHECKOUT NOS DADOS ANTES DE DELETAR
SELECT * FROM ATTENDEE
WHERE PHONE IS NULL AND EMAIL IS NULL;

DELETE FROM ATTENDEE
WHERE PHONE IS NULL AND EMAIL IS NULL;

-- TRUNCATE TABLE
-- UTILIZADO NO MySQL o SQLite NAO SUPORTA TRUNCATE
TRUNCATE TABLE ATTENDEE;

-- UPDATE
UPDATE ATTENDEE
SET EMAIL = UPPER(EMAIL);

UPDATE ATTENDEE
SET FIRST_NAME = UPPER(FIRST_NAME), LAST_NAME = UPPER(LAST_NAME);

UPDATE ATTENDEE 
SET VIP = 1
WHERE ATTENDEE_ID IN (3, 4);

SELECT * FROM ATTENDEE;

--DROP TABLE
CREATE TABLE MY_UNWANTE_TABLE();

DROP TABLE MY_UNWANTED_TABLE;

