-- O SQLite faz o autoincrement automaticamente, porem outras SGBD's nao
CREATE TABLE COMPANY(
    COMPANY_ID INTEGER PRIMARY KEY AUTOINCREMENT ,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(60),
    PRIMARY_CONTACT_ATTENDEE_ID INTEGER NOT NULL
                                        REFERENCES ATTENDEE(ATTENDEE_ID)
);


CREATE TABLE ROOM(
    ROOM_ID INTEGER PRIMARY KEY,
    FLOOR_NUMER INTEGER NOT NULL,
    SEAT_CAPACITY INTEGER NOT NULL  
);

CREATE TABLE PRESENTATION(
    PRESENTATION_ID INTEGER PRIMARY KEY,
    BOOKED_COMPANY_ID INTEGER NOT NULL 
                              REFERENCES COMPANY(COMPANY_ID),
    BOOKED_ROOM_ID INTEGER NOT NULL
                           REFERENCES ROOM(ROOM_ID),
    START_TIME TIME,
    END_TIME TIME
);


CREATE TABLE ATTENDEE(
    ATTENDEE_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    PHONE INTEGER,
    EMAIL VARCHAR(30),
    VIP BOOLEAN DEFAULT(0)
);

CREATE TABLE PRESENTATION_ATTENDANCE(
    TICKET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRESENTATION_ID INTEGER REFERENCES PRESENTATION(PRESENTATION_ID),
    ATTENDEE_ID INTEGER REFERENCES ATTENDEE(ATTENDEE_ID)
);

-- CRIANDO VIEWS
CREATE VIEW PRESENTATION_VW AS
    SELECT
        COMPANY.NAME AS BOOKED_COMPANY,
        ROOM.ROOM_ID AS ROOM_NUMBER,
        ROOM.FLOOR_NUMER AS FLOOR,
        ROOM.SEAT_CAPACITY AS SEATS,
        START_TIME,
        END_TIME
    FROM PRESENTATION
        INNER JOIN COMPANY
        ON PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID
        INNER JOIN ROOM
    ON PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;
    
SELECT * FROM PRESENTATION_VW
WHERE SEAT_CAPACITY >= 30;