CREATE TABLE PAIS (
ID INT PRIMARY KEY,
NOME VARCHAR(30)
)


INSERT INTO PAIS VALUES(1,	'Brasil'), 
INSERT INTO PAIS VALUES(2,	'Estados Unidos')


SELECT * FROM PAIS


CREATE TABLE ESTADO (
ID INT PRIMARY KEY,
NOME VARCHAR(30),
COD_PAIS INT NOT NULL FOREIGN KEY REFERENCES PAIS(ID) 
)

INSERT INTO ESTADO VALUES (1, 'Distrito Federal', 1);
INSERT INTO ESTADO VALUES (2, 'Minas Gerais', 1);
INSERT INTO ESTADO VALUES (3, 'Florida', 2);
INSERT INTO ESTADO VALUES (4, 'Sao Paulo', 1);

SELECT * FROM ESTADO

--DELETE FROM ESTADO
-- WHERE COD_PAIS = 2

SELECT * FROM PAIS AS P
INNER JOIN ESTADO AS E
ON P.ID = E.COD_PAIS,

SELECT 
P.NOME AS NOME_PAIS,
E.NOME AS NOME_ESTADO
FROM PAIS AS P
INNER JOIN ESTADO AS E
ON P.ID = E.COD_PAIS