CREATE TABLE TABELA (
	ID INT,
	NOME VARCHAR(30)
)

INSERT INTO TABELA VALUES(1, 'WESLLEY')
INSERT INTO TABELA VALUES(2, 'LHAIS')
INSERT INTO TABELA VALUES(3, 'MADALENA')
INSERT INTO TABELA VALUES(4, 'WILLIAM')


SELECT * FROM TABELA

SELECT * FROM TABELA
WHERE ID > 1

CREATE VIEW VW_VIEW1 AS
SELECT * FROM TABELA
WHERE ID > 1

SELECT * FROM TABELA
SELECT * FROM VW_VIEW1


SELECT * FROM TABELA
WHERE ID >= 2 AND NOME = 'LHAIS'

SELECT * FROM TABELA
WHERE ID >= 2 OR NOME = 'WESLLEY'


--DROP VIEW VW_VIEW1

SELECT * FROM TABELA

-- CRIOU UMA VIEW COM BASE NO SELECT WHERE
CREATE VIEW VISUALIZACAO AS
SELECT * FROM TABELA
WHERE ID > 1


CREATE TABLE TABELA2 AS
SELECT * FROM TABELA
WHERE ID > 1

-- CRIOU UMA TABELA COM BASE NO SELECT WHERE
SELECT * INTO TABELA2
FROM TABELA
WHERE ID > 1
 
SELECT * FROM TABELA2


